Algoritmo "question_five"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/08/2020
Var
// Seção de Declarações das variáveis 
numero:inteiro
contador:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para contador de 100 ate 1 passo -2 faca
escreval (contador)
fimpara

Fimalgoritmo